export const ragOverview = "RAG (retrieval-augmented generation) connects a language model to a changeable knowledge source. A production pipeline usually has these stages:\n\n1. Ingest: parse files, preserve metadata and permissions, and split content into overlapping or structure-aware chunks.\n2. Index: create embeddings and a lexical index; keep both linked to source IDs and versions.\n3. Retrieve: rewrite or expand the question, apply access filters, then combine semantic and keyword search.\n4. Rerank: score the strongest passages against the actual question and remove duplicates.\n5. Answer: fit the best evidence into the context window, instruct the model to cite it, and say when evidence is missing.\n6. Evaluate: measure retrieval recall, answer faithfulness, citation accuracy, latency, and cost against a representative test set.\n\nAdvanced patterns include hybrid retrieval, parent-child chunks, query decomposition, multi-hop GraphRAG, corrective or agentic retrieval, and multimodal indexes. These add complexity; use an evaluation set to show they improve your real questions. RAG can ground answers in retrieved material, but it does not guarantee truth or remove prompt-injection and data-access risks.";

const quickAnswers: { test: RegExp; answer: string; suggestions: string[] }[] = [
  { test: /\b(?:what is|explain|teach me about|advanced|high[- ]level).*\b(?:rag|retrieval[- ]augmented generation)\b/i, answer: ragOverview, suggestions: ["Explore vector databases", "Find RAG projects", "What is GraphRAG?"] },
  { test: /\bwhat is (?:a )?vector database\b/i, answer: "A vector database stores numerical representations of items (embeddings) and retrieves items whose vectors are close to a query vector. It is commonly used for semantic search and as the retrieval step in RAG systems.", suggestions: ["Find vector database projects", "What is an embedding?", "Explore RAG"] },
  { test: /\bwhat is (?:an? )?embedding\b/i, answer: "An embedding is a list of numbers that represents content such as text or an image. Similar content tends to have nearby vectors, which lets software search by meaning instead of only matching exact words.", suggestions: ["Find embedding projects", "Explore vector databases", "What is RAG?"] },
  { test: /\bwhat is graphrag\b/i, answer: "GraphRAG combines retrieval-augmented generation with a graph of entities and their relationships. The graph can help answer questions that require connecting information across multiple sources, while retrieved source text grounds the response.", suggestions: ["Find GraphRAG projects", "What is RAG?", "Explore knowledge graphs"] },
  { test: /\bwhat is fastapi\b/i, answer: "FastAPI is a Python framework for building HTTP APIs. It uses Python type hints to validate request data and generate an OpenAPI description, and it supports asynchronous handlers.", suggestions: ["Find FastAPI projects", "Explore Python APIs", "What is an API?"] },
  { test: /\bwhat is (?:machine learning|ml)\b/i, answer: "Machine learning is a way to build software that learns patterns from examples and uses them to make predictions or decisions, instead of relying only on hand-written rules. Models need suitable data and evaluation to show whether those patterns generalize.", suggestions: ["Find beginner machine learning projects", "Explore AI", "What is an embedding?"] },
];

export function offlineAnswer(message: string) {
  return quickAnswers.find(item => item.test.test(message)) ?? null;
}
