import type { Candidate } from "@/lib/ranking";

type Idea = { title: string; domain: string; type: string; description: string; image?: string | null; url?: string; details?: string[]; genres?: string[]; keywords?: string[]; provider?: string; id: string };
const shelves: Record<string, Idea[]> = {
  rag: [
    { id:"langchain-ai/langchain", title:"LangChain", domain:"code", type:"repository", provider:"github", url:"https://github.com/langchain-ai/langchain", description:"Build applications that connect language models to retrievers, tools, and data sources.", genres:["RAG","LLM applications"], details:["If you like RAG, explore agentic retrieval next." ] },
    { id:"run-llama/llama_index", title:"LlamaIndex", domain:"code", type:"repository", provider:"github", url:"https://github.com/run-llama/llama_index", description:"A data framework for indexing private and domain-specific information for LLM applications.", genres:["RAG","Data frameworks"], details:["Try document parsing and hybrid retrieval."] },
    { id:"facebookresearch/faiss", title:"FAISS", domain:"code", type:"repository", provider:"github", url:"https://github.com/facebookresearch/faiss", description:"A library for efficient similarity search and clustering of dense vectors.", genres:["Vector search","Embeddings"], details:["A useful next step when learning RAG retrieval."] },
    { id:"AI Engineering", title:"AI Engineering", domain:"book", type:"book", provider:"curated", url:"https://www.oreilly.com/library/view/ai-engineering/9781098166298/", description:"Chip Huyen’s practical guide to building applications powered by foundation models.", genres:["LLM applications","RAG"], details:["Good follow-on reading for production RAG systems."] },
    { id:"Designing Data-Intensive Applications", title:"Designing Data-Intensive Applications", domain:"book", type:"book", provider:"curated", url:"https://dataintensive.net/", description:"Martin Kleppmann’s guide to data systems, storage, indexing, and distributed processing.", genres:["Data systems","Search"], details:["Builds useful background for retrieval pipelines."] },
    { id:"GraphRAG", title:"GraphRAG", domain:"code", type:"topic", provider:"curated", url:"https://github.com/microsoft/graphrag", description:"A graph-based approach to retrieval for questions that connect information across a corpus.", genres:["Knowledge graphs","RAG"], details:["Try this when ordinary similarity search misses relationships."] },
  ],
  crime: [
    { id:"949", title:"Heat", domain:"movie", type:"movie", provider:"tmdb", url:"https://www.themoviedb.org/movie/949", description:"A methodical crime drama about a master thief and the detective tracking him.", genres:["Crime","Drama"], details:["If you like tense professional rivalries, try The Departed next."] },
    { id:"238", title:"The Godfather", domain:"movie", type:"movie", provider:"tmdb", url:"https://www.themoviedb.org/movie/238", description:"A family crime saga about power, loyalty, and succession.", genres:["Crime","Drama"], details:["Try a book about power and institutions alongside it."] },
    { id:"The Departed", title:"The Departed", domain:"movie", type:"movie", provider:"curated", image:"https://image.tmdb.org/t/p/w500/nT97ifVT2J1yMQmeq20Qblg61T.jpg", url:"https://www.themoviedb.org/movie/1422-the-departed", description:"A crime thriller about two infiltrators working on opposite sides of a Boston gang war.", genres:["Crime","Thriller"], details:["If you like Heat’s cat-and-mouse tension, try this next."] },
    { id:"Collateral", title:"Collateral", domain:"movie", type:"movie", provider:"curated", image:"https://image.tmdb.org/t/p/w500/nV5316WUsVij8sVXLCF1g7TFitg.jpg", url:"https://www.themoviedb.org/movie/1538-collateral", description:"A night-long Los Angeles thriller about a cab driver and a contract killer.", genres:["Crime","Thriller"], details:["Try this for another Michael Mann story set over one night."] },
    { id:"Thief", title:"Thief", domain:"movie", type:"movie", provider:"curated", url:"https://www.themoviedb.org/search?query=Thief", description:"Michael Mann’s crime film about a professional safecracker trying to leave his old life behind.", genres:["Crime","Drama"], details:["A close next watch for Heat’s director, craft, and criminal world."] },
    { id:"Goodfellas", title:"Goodfellas", domain:"movie", type:"movie", provider:"curated", url:"https://www.themoviedb.org/search?query=Goodfellas", description:"A crime drama following a mob associate’s rise and fall over several decades.", genres:["Crime","Drama"], details:["Try this for a faster, voice-driven crime saga."] },
    { id:"The Friends of Eddie Coyle", title:"The Friends of Eddie Coyle", domain:"book", type:"book", provider:"curated", url:"https://openlibrary.org/search?q=The+Friends+of+Eddie+Coyle", description:"George V. Higgins’s crime novel, known for its sharp, naturalistic dialogue.", genres:["Crime fiction"], details:["A grounded, dialogue-led follow-up to crime cinema."] },
    { id:"The Power of the Dog", title:"The Power of the Dog", domain:"book", type:"book", provider:"curated", url:"https://openlibrary.org/search?q=The+Power+of+the+Dog+Don+Winslow", description:"Don Winslow’s sprawling crime novel about the drug trade and law enforcement.", genres:["Crime","Thriller"], details:["Try this for a longer, multi-perspective crime story."] },
  ],
  strategy: [
    { id:"The Prince", title:"The Prince", domain:"book", type:"book", provider:"curated", url:"https://openlibrary.org/search?q=The+Prince+Machiavelli", description:"Niccolò Machiavelli’s short political treatise on power and statecraft.", genres:["Political philosophy","Strategy"], details:["If you like strategic power dynamics, try The Art of War next."] },
    { id:"The Art of War", title:"The Art of War", domain:"book", type:"book", provider:"curated", url:"https://openlibrary.org/search?q=The+Art+of+War+Sun+Tzu", description:"Sun Tzu’s classic text on conflict, preparation, and decision-making.", genres:["Strategy","History"], details:["A compact companion read on planning under uncertainty."] },
    { id:"The 48 Laws of Power", title:"The 48 Laws of Power", domain:"book", type:"book", provider:"curated", url:"https://openlibrary.org/search?q=The+48+Laws+of+Power", description:"Robert Greene’s collection of historical case studies and maxims about influence and power.", genres:["Strategy","History"], details:["If you like The Prince, compare its modern case-study style with Machiavelli."] },
    { id:"The Strategy of Conflict", title:"The Strategy of Conflict", domain:"book", type:"book", provider:"curated", url:"https://openlibrary.org/search?q=The+Strategy+of+Conflict+Schelling", description:"Thomas Schelling’s influential study of bargaining, commitment, and strategic interaction.", genres:["Game theory","Strategy"], details:["Try this for a more analytical take on strategy."] },
    { id:"The Social Network", title:"The Social Network", domain:"movie", type:"movie", provider:"curated", url:"https://www.themoviedb.org/search?query=The%20Social%20Network", description:"A drama about ambition, collaboration, and conflict around a fast-growing company.", genres:["Drama","Business"], details:["If you like strategy in institutions, try Succession next."] },
    { id:"Moneyball", title:"Moneyball", domain:"movie", type:"movie", provider:"curated", url:"https://www.themoviedb.org/search?query=Moneyball", description:"A sports drama about using evidence and unconventional thinking to compete.", genres:["Drama","Strategy"], details:["Try this for decision-making under tight constraints."] },
  ],
  romance: [
    { id:"Pride and Prejudice", title:"Pride and Prejudice", domain:"book", type:"book", provider:"curated", url:"https://openlibrary.org/search?q=Pride+and+Prejudice", description:"Jane Austen’s novel of first impressions, social expectations, and affection.", genres:["Romance","Classic"], details:["If you like witty slow-burn romance, try Emma next."] },
    { id:"Before Sunrise", title:"Before Sunrise", domain:"movie", type:"movie", provider:"curated", url:"https://www.themoviedb.org/search?query=Before%20Sunrise", description:"A two-person conversation unfolds over one night in Vienna.", genres:["Romance","Drama"], details:["Try this for intimate, dialogue-led romance."] },
    { id:"Normal People", title:"Normal People", domain:"book", type:"book", provider:"curated", url:"https://openlibrary.org/search?q=Normal+People+Sally+Rooney", description:"Sally Rooney’s novel follows an evolving relationship and its communication gaps.", genres:["Romance","Literary fiction"], details:["Try it for a contemporary, emotionally restrained story."] },
  ],
  "hip hop": [
    { id:"To Pimp a Butterfly", title:"To Pimp a Butterfly", domain:"music", type:"album", provider:"curated", url:"https://music.apple.com/us/search?term=To%20Pimp%20a%20Butterfly", description:"Kendrick Lamar’s jazz-inflected album about identity, fame, and Black American life.", genres:["Hip-hop","Jazz rap"], details:["If you like its jazz and spoken-word textures, try A Tribe Called Quest next."] },
    { id:"A Tribe Called Quest", title:"A Tribe Called Quest", domain:"music", type:"artist", provider:"curated", url:"https://music.apple.com/us/search?term=A%20Tribe%20Called%20Quest", description:"A foundational hip-hop group whose sound draws on jazz samples and relaxed, conversational flows.", genres:["Hip-hop","Jazz rap"], details:["A natural next listen for jazz-influenced hip-hop."] },
    { id:"good kid, m.A.A.d city", title:"good kid, m.A.A.d city", domain:"music", type:"album", provider:"curated", url:"https://music.apple.com/us/search?term=good%20kid%20m.A.A.d%20city", description:"Kendrick Lamar’s narrative album about adolescence and Compton.", genres:["Hip-hop","West Coast rap"], details:["Try this for a tightly sequenced story album."] },
    { id:"The Miseducation of Lauryn Hill", title:"The Miseducation of Lauryn Hill", domain:"music", type:"album", provider:"curated", url:"https://music.apple.com/us/search?term=The%20Miseducation%20of%20Lauryn%20Hill", description:"Lauryn Hill’s solo album blends hip-hop, soul, and R&B with personal songwriting.", genres:["Hip-hop","Neo soul"], details:["If you like concept-driven hip-hop, try its mix of songs and interludes."] },
  ],
  "alternative rock": [
    {id:"Roads",title:"Roads",domain:"music",type:"track",provider:"curated",url:"https://music.apple.com/us/search?term=Roads%20Portishead",description:"Portishead’s slow-burning song builds a stark, intimate mood from a trip-hop pulse and Beth Gibbons’s vocal.",genres:["Trip-hop","Alternative"],details:["Try it for the shadowy production and emotional restraint that Radiohead listeners often enjoy."]},
    {id:"Teardrop",title:"Teardrop",domain:"music",type:"track",provider:"curated",url:"https://music.apple.com/us/search?term=Teardrop%20Massive%20Attack",description:"Massive Attack’s atmospheric song layers a delicate vocal over a patient, hypnotic beat.",genres:["Trip-hop","Electronic"],details:["Try it for detailed production and a spacious, melancholic atmosphere."]},
    {id:"Svefn-g-englar",title:"Svefn-g-englar",domain:"music",type:"track",provider:"curated",url:"https://music.apple.com/us/search?term=Svefn-g-englar%20Sigur%20Ros",description:"Sigur Rós’s slow-building post-rock track turns voice, strings, and guitar into a wide cinematic soundscape.",genres:["Post-rock","Alternative"],details:["Try it for patient arrangements and an immersive atmosphere."]},
    {id:"Dayvan Cowboy",title:"Dayvan Cowboy",domain:"music",type:"track",provider:"curated",url:"https://music.apple.com/us/search?term=Dayvan%20Cowboy%20Boards%20of%20Canada",description:"Boards of Canada’s instrumental drifts from dusty electronics into a broad, guitar-led crescendo.",genres:["Electronic","Ambient"],details:["Try it for a more electronic route into layered, expansive sound."]},
    {id:"Heaven or Las Vegas",title:"Heaven or Las Vegas",domain:"music",type:"track",provider:"curated",url:"https://music.apple.com/us/search?term=Heaven%20or%20Las%20Vegas%20Cocteau%20Twins",description:"Cocteau Twins pair shimmering guitar textures with an airy, dreamlike vocal performance.",genres:["Dream pop","Alternative"],details:["Try it for bright, layered guitar and an abstract vocal style."]},
    {id:"In Rainbows",title:"In Rainbows",domain:"music",type:"album",provider:"curated",url:"https://music.apple.com/us/search?term=In%20Rainbows",description:"Radiohead’s 2007 album pairs layered production with intimate songwriting.",genres:["Alternative rock","Art rock"],details:["If you like its warm, detailed sound, try Hail to the Thief next."]},
    {id:"Talk Talk",title:"Talk Talk",domain:"music",type:"artist",provider:"curated",url:"https://music.apple.com/us/search?term=Talk%20Talk",description:"An influential band whose later work moved from synth-pop toward spacious, experimental rock.",genres:["Art rock","Post-rock"],details:["A good next listen for Radiohead’s more atmospheric side."]},
    {id:"Portishead",title:"Portishead",domain:"music",type:"artist",provider:"curated",url:"https://music.apple.com/us/search?term=Portishead",description:"A Bristol group blending trip-hop, live instrumentation, and cinematic production.",genres:["Trip-hop","Alternative"],details:["Try this if you like moody textures and precise production."]},
    {id:"Dummy",title:"Dummy",domain:"music",type:"album",provider:"curated",url:"https://music.apple.com/us/search?term=Dummy%20Portishead",description:"Portishead’s debut album, built around smoky vocals, samples, and a noir atmosphere.",genres:["Trip-hop","Alternative"],details:["A neighboring path from art rock into trip-hop."]},
  ],
  jazz: [
    { id:"Kind of Blue", title:"Kind of Blue", domain:"music", type:"album", provider:"curated", url:"https://music.apple.com/us/search?term=Kind%20of%20Blue", description:"Miles Davis’s landmark modal jazz album, recorded in 1959.", genres:["Jazz","Modal jazz"], details:["If you like its open, spacious sound, try In a Silent Way next."] },
    { id:"In a Silent Way", title:"In a Silent Way", domain:"music", type:"album", provider:"curated", url:"https://music.apple.com/us/search?term=In%20a%20Silent%20Way", description:"Miles Davis’s atmospheric studio album, pointing toward jazz fusion.", genres:["Jazz","Jazz fusion"], details:["A good next listen for ambient, electric jazz."] },
    { id:"Blue Train", title:"Blue Train", domain:"music", type:"album", provider:"curated", url:"https://music.apple.com/us/search?term=Blue%20Train", description:"John Coltrane’s hard-bop album, released in 1957.", genres:["Jazz","Hard bop"], details:["Try it for a more driving small-group sound."] },
  ],
  "science fiction": [
    {id:"Arrival",title:"Arrival",domain:"movie",type:"movie",provider:"curated",url:"https://www.themoviedb.org/search?query=Arrival",description:"A science-fiction drama about language, communication, and first contact.",genres:["Science fiction","Drama"],details:["If you like thoughtful first-contact stories, try Contact next."]},
    {id:"The Left Hand of Darkness",title:"The Left Hand of Darkness",domain:"book",type:"book",provider:"curated",url:"https://openlibrary.org/search?q=The+Left+Hand+of+Darkness",description:"Ursula K. Le Guin’s science-fiction novel about culture, identity, and diplomacy.",genres:["Science fiction","Social science fiction"],details:["Try it for world-building centered on society and identity."]},
    {id:"2001: A Space Odyssey",title:"2001: A Space Odyssey",domain:"movie",type:"movie",provider:"curated",url:"https://www.themoviedb.org/search?query=2001%20A%20Space%20Odyssey",description:"A science-fiction film about evolution, technology, and an enigmatic mission.",genres:["Science fiction","Adventure"],details:["If you like slow, idea-driven sci-fi, try Solaris next."]},
    {id:"Project Hail Mary",title:"Project Hail Mary",domain:"book",type:"book",provider:"curated",url:"https://openlibrary.org/search?q=Project+Hail+Mary",description:"Andy Weir’s science-fiction novel about an astronaut solving a survival problem far from Earth.",genres:["Science fiction","Adventure"],details:["Try it for a puzzle-solving, high-stakes space story."]},
  ],
  horror: [
    {id:"Get Out",title:"Get Out",domain:"movie",type:"movie",provider:"curated",url:"https://www.themoviedb.org/search?query=Get%20Out",description:"A horror film that uses a tense visit to explore race, power, and social performance.",genres:["Horror","Thriller"],details:["If you like social horror, try His House next."]},
    {id:"The Haunting of Hill House",title:"The Haunting of Hill House",domain:"book",type:"book",provider:"curated",url:"https://openlibrary.org/search?q=The+Haunting+of+Hill+House",description:"Shirley Jackson’s psychological haunted-house novel.",genres:["Horror","Gothic fiction"],details:["Try it for dread built through voice and atmosphere."]},
    {id:"The Thing",title:"The Thing",domain:"movie",type:"movie",provider:"curated",url:"https://www.themoviedb.org/search?query=The%20Thing",description:"John Carpenter’s science-fiction horror about isolation and mistrust in Antarctica.",genres:["Horror","Science fiction"],details:["If you like paranoia and isolation, try Alien next."]},
  ],
  fantasy: [
    {id:"A Wizard of Earthsea",title:"A Wizard of Earthsea",domain:"book",type:"book",provider:"curated",url:"https://openlibrary.org/search?q=A+Wizard+of+Earthsea",description:"Ursula K. Le Guin’s fantasy novel about a young mage, responsibility, and balance.",genres:["Fantasy","Coming of age"],details:["Try it for thoughtful, character-led fantasy."]},
    {id:"Spirited Away",title:"Spirited Away",domain:"movie",type:"movie",provider:"curated",url:"https://www.themoviedb.org/search?query=Spirited%20Away",description:"A fantasy film about a girl navigating a strange spirit world.",genres:["Fantasy","Animation"],details:["If you like imaginative worlds, try The Boy and the Heron next."]},
    {id:"The Hobbit",title:"The Hobbit",domain:"book",type:"book",provider:"curated",url:"https://openlibrary.org/search?q=The+Hobbit",description:"J. R. R. Tolkien’s adventure about a reluctant traveler drawn into a quest.",genres:["Fantasy","Adventure"],details:["A classic next step for quest-driven fantasy."]},
  ],
};

export function inspirationTopic(input: string, signals: string[] = []) {
  const text = `${input} ${signals.join(" ")}`.toLowerCase();
  const aliases: [string, RegExp][] = [["rag", /\b(rag|retrieval[- ]augmented generation|graphrag|vector database|embeddings?)\b/], ["crime", /\b(crime|gangster|heist|mafia|detective|thriller|heat|goodfellas|scarface|godfather)\b/], ["science fiction", /\b(science fiction|sci[- ]?fi|space opera|dune|arrival|solaris)\b/], ["horror", /\b(horror|haunted|paranormal|slasher|get out|the thing)\b/], ["fantasy", /\b(fantasy|magic|magical|mythic|earthsea|the hobbit|spirited away)\b/], ["strategy", /\b(strategy|ambition|power|leadership|decision making|the prince|art of war|moneyball)\b/], ["romance", /\b(romance|romantic|love|heartbreak|pride and prejudice|before sunrise)\b/], ["hip hop", /\b(hip[- ]?hop|rap|kendrick|jazz rap|pimp a butterfly|good kid)\b/], ["alternative rock", /\b(radiohead|alternative rock|indie rock|trip hop|portishead|talk talk)\b/], ["jazz", /\bjazz\b/]];
  return aliases.find(([, pattern]) => pattern.test(text))?.[0] ?? null;
}

export function getInspiration(input: string, signals: string[] = [], domain?: string): Candidate[] {
  const topic = inspirationTopic(input, signals);
  const shelf = topic ? (shelves[topic] ?? []) : [];
  const seedMatch = input.match(/\b(heat|goodfellas|scarface|the godfather|dune|arrival|solaris|get out|the thing|a wizard of earthsea|the hobbit|spirited away|the prince|the art of war|the 48 laws of power|the strategy of conflict|moneyball|pride and prejudice|before sunrise|to pimp a butterfly|good kid,? m\.a\.a\.d city|the miseducation of lauryn hill|kind of blue|in a silent way|radiohead|in rainbows|dummy)\b/i)?.[0].toLowerCase();
  const withoutSeed = seedMatch ? shelf.filter(item => item.title.toLowerCase() !== seedMatch) : shelf;
  const wantsTracks = /\b(songs?|tracks?)\b/i.test(input);
  const formatFiltered = wantsTracks ? withoutSeed.filter(item => item.type === "track") : withoutSeed;
  const chosen = domain ? formatFiltered.filter(item => item.domain === domain || domain === "movie" && item.domain === "tv") : formatFiltered;
  const label = input.trim().slice(0,80) || "discovery";
  const encoded = encodeURIComponent(label);
  const directories: Idea[] = [
    {id:`movie:${label}`,title:`Films about “${label}”`,domain:"movie",type:"catalog-search",provider:"catalog-link",url:`https://www.themoviedb.org/search?query=${encoded}`,description:`Open a film and TV catalog search for “${label}”. Use the results to follow its themes, genres, or creators.`,genres:[topic??label],details:["If you find a title you like, search its director or shared themes next."]},
    {id:`book:${label}`,title:`Books about “${label}”`,domain:"book",type:"catalog-search",provider:"catalog-link",url:`https://openlibrary.org/search?q=${encoded}`,description:`Browse books matching “${label}”, including different subjects and authors.`,genres:[topic??label],details:["Try a neighboring subject or an author from a result."]},
    {id:`music:${label}`,title:`Music connected to “${label}”`,domain:"music",type:"catalog-search",provider:"catalog-link",url:`https://music.apple.com/us/search?term=${encoded}`,description:`Explore albums, artists, and tracks related to “${label}”.`,genres:[topic??label],details:["If one artist stands out, follow their collaborators and influences."]},
    {id:`code:${label}`,title:`Projects about “${label}”`,domain:"code",type:"catalog-search",provider:"catalog-link",url:`https://github.com/search?q=${encoded}&type=repositories`,description:`Search open source repositories for “${label}” and compare approaches, languages, and activity.`,genres:[topic??label],details:["Try a related keyword or filter by programming language."]},
  ];
  const useShelf = chosen.length ? chosen : directories.filter(item => !domain || item.domain === domain);
  return useShelf.map(item => ({ ...item, details: item.details ?? [], genres: item.genres ?? [], keywords: item.keywords ?? [], sources:[chosen.length?"editorial-inspiration":"catalog-search-link"], evidence:{signals:[topic ?? label]}, provider_data:{provider_id:item.id, curated:true} })) as Candidate[];
}

export function inspirationSuggestions(input: string, signals: string[] = []) {
  const topic = inspirationTopic(input, signals);
  const related: Record<string,string[]> = {
    rag:["Vector databases","Semantic search","GraphRAG","Document parsing","Hybrid retrieval","LlamaIndex projects","FAISS projects","AI Engineering book"],
    crime:["Neo-noir films","Caper novels","True-crime documentaries","Heist stories","Power and loyalty","If you like Heat, try The Departed"],
    "science fiction":["First-contact stories","Space opera","Speculative fiction","Thoughtful sci-fi films","If you like Arrival, try Contact"],
    horror:["Psychological horror","Social horror","Gothic novels","Creature features","If you like Get Out, try His House"],
    fantasy:["Quest fantasy","Mythic worlds","Animated fantasy","Coming-of-age magic","If you like Earthsea, try The Hobbit"],
    strategy:["Decision-making books","Political dramas","Game theory","Leadership biographies","If you like The Prince, try The Art of War"],
    romance:["Slow-burn films","Contemporary love stories","Romantic comedies","Witty classics","If you like Before Sunrise, try Past Lives"],
    "hip hop":["Jazz rap","Storytelling albums","Conscious hip-hop","A Tribe Called Quest","If you like To Pimp a Butterfly, try The Miseducation of Lauryn Hill"],
    "alternative rock":["Art rock","Trip-hop","Post-rock","Atmospheric albums","If you like Radiohead, try Portishead"],
    jazz:["Modal jazz","Hard bop","Jazz fusion","Vocal jazz","If you like Kind of Blue, try In a Silent Way"],
  };
  if (!topic) { const label=input.trim().slice(0,60)||"this topic"; return [`Films related to ${label}`,`Books about ${label}`,`Music connected to ${label}`,`Open-source ${label} projects`,`Try a neighboring keyword`,`Follow an author, artist, or creator`,`Explore a different medium`,`Surprise me`]; }
  return (related[topic] ?? ["Films","Books","Music","Creative projects","A related topic","Surprise me"]).slice(0,8);
}

export function getCrossDomainInspiration(input: string, signals: string[] = []) {
  const topic = inspirationTopic(input, signals);
  const source:Idea[] = topic ? shelves[topic] ?? [] : getInspiration(input).flatMap(item=>item.domain?[{id:String(item.id),title:item.title,domain:item.domain,type:item.type,description:item.description??"",url:item.url,details:item.details,genres:item.genres}]:[]);
  const buckets=new Map<string,Idea[]>();for(const item of source){const items=buckets.get(item.domain)??[];items.push(item);buckets.set(item.domain,items);}
  const selected:Idea[]=[];while(selected.length<6){let added=false;for(const items of buckets.values()){if(items.length){selected.push(items.shift()!);added=true;if(selected.length===6)break;}}if(!added)break;}
  return selected.map(item => ({ title:item.title, url:item.url, domain:item.domain, description:`${item.description} ${item.details?.[0] ?? "A useful search path related to this topic."}` }));
}
