import Link from "next/link";
import Image from "next/image";
import { ArrowLeft, ArrowRight, Compass, LockKeyhole, Orbit } from "lucide-react";

export default async function LoginPage({ searchParams }: { searchParams: Promise<{ auth?: string; mode?: string }> }) {
  const { auth, mode: requestedMode } = await searchParams;
  const mode = requestedMode === "signup" ? "signup" : "signin";
  const ready = Boolean(process.env.GOOGLE_CLIENT_ID && process.env.GOOGLE_CLIENT_SECRET && process.env.DATABASE_URL && process.env.AUTH_SECRET && process.env.AUTH_SECRET.length >= 32);
  return <main className="login-page"><Link className="login-back" href="/"><ArrowLeft size={15}/> Back to exploring</Link><section className="login-sheet"><div className="sketch-orbit"><span/><i/><b/><Orbit size={92}/></div><div className="eyebrow"><span className="eyebrow-line"/> A FIELD GUIDE TO WHAT MOVES YOU</div><div className="auth-switch" role="tablist" aria-label="Account access"><Link role="tab" aria-selected={mode==="signin"} className={mode==="signin"?"active":""} href="/login?mode=signin">Sign in</Link><Link role="tab" aria-selected={mode==="signup"} className={mode==="signup"?"active":""} href="/login?mode=signup">Create account</Link></div><h1>{mode==="signup"?<>Start your<br/><i>field guide.</i></>:<>Welcome<br/><i>back.</i></>}</h1><p>{mode==="signup"?"Create your account with Google. If this is your first visit, we’ll start a private taste map for you.":"Sign in with Google to return to your saved discoveries and taste map."}</p>{auth&&auth!=="success"&&<div className="login-error" role="alert">{auth==="unavailable"?"Google sign-in is not configured yet.":"Sign-in did not complete. Please try again."}</div>}{auth==="success"&&<div className="login-success" role="status">Your Google account is connected. Your taste map is ready to grow.</div>}{ready?<a className="google-cta" href={`/api/auth/google?mode=${mode}`}><Image src="https://www.gstatic.com/firebasejs/ui/2.0.0/images/auth/google.svg" alt="" width={19} height={19} unoptimized/> {mode==="signup"?"Sign up with Google":"Continue with Google"} <ArrowRight size={16}/></a>:<><button className="google-cta google-disabled" type="button" disabled><Image src="https://www.gstatic.com/firebasejs/ui/2.0.0/images/auth/google.svg" alt="" width={19} height={19} unoptimized/> {mode==="signup"?"Sign up with Google":"Continue with Google"} <ArrowRight size={16}/></button><div className="login-setup"><LockKeyhole size={16}/><span>Enable Google access by setting <code>GOOGLE_CLIENT_ID</code>, <code>GOOGLE_CLIENT_SECRET</code>, and <code>DATABASE_URL</code> in <code>.env.local</code>.</span></div></>}<small>Google securely creates an account on your first visit and signs you back in on later visits. Only your chosen taste summary can be shared.</small><div className="login-signal">SIGNAL 01 <span/> YOUR WORLD IS STILL FORMING</div></section><footer className="login-footer"><span><Compass size={15}/> FIND YOUR NICHE</span><span>YOUR TASTE IS ALWAYS BECOMING</span></footer></main>;
}
