"use client";
import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import { ArrowRight, Compass, LoaderCircle } from "lucide-react";
import { CrtBackground } from "@/shaders/crt/CrtBackground";

type Signal = { name: string; node_type: string; weight: number };
type Result = { shared: string[]; theirs: Signal[]; yours: Signal[]; viewerAvailable: boolean; ownerIdentity: { displayName: string; tasteId: string } };
export function CompareView() {
  const params = useParams<{ token: string }>(); const token = params.token;
  const [data, setData] = useState<Result | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  useEffect(() => { let active = true; (async () => { try { await fetch("/api/session").catch(() => null); const res = await fetch(`/api/compare/${encodeURIComponent(token)}`); const body = await res.json(); if (!res.ok) throw new Error(body.error ?? "This comparison is unavailable."); if (active) setData(body); } catch (e) { if (active) setError(e instanceof Error ? e.message : "This comparison is unavailable."); } finally { if (active) setLoading(false); } })(); return () => { active = false; }; }, [token]);
  return <main className="compare-page"><div className="compare-crt" aria-hidden="true"><CrtBackground variant="cinematic" opacity={0.62} motion={0.38}/></div><nav className="compare-nav"><Link href="/" className="brand"><span className="brand-mark"><Compass size={18}/></span> find your <b>niche</b><span className="brand-dot">.</span></Link><Link href="/">Explore <ArrowRight size={14}/></Link></nav><section className="compare-hero"><div className="eyebrow"><span className="eyebrow-line"/> A SHARED FIELD GUIDE</div><p className="compare-kicker">TASTE SIGNAL / 001</p><h1>Two worlds.<br/><i>New territory.</i></h1>{loading?<div className="compare-loading"><div className="compare-loader"><LoaderCircle className="spin" size={22}/></div><p>MAPPING YOUR CONNECTIONS</p></div>:error?<div className="compare-error" role="alert"><b>This link can’t be opened.</b><span>{error}</span><Link href="/login">Continue with Google <ArrowRight size={14}/></Link></div>:data?<><p className="compare-intro">A private comparison built from broad taste signals. Searches and activity history remain private.</p><div className="shared-identity"><span>SHARED BY</span><b>{data.ownerIdentity.displayName}</b><code>TASTE ID · {data.ownerIdentity.tasteId.toUpperCase()}</code></div><div className="compare-columns"><article><small>SHARED RABBIT HOLE</small><h2>{data.shared.length?`${data.shared.length} common signals`:"Still finding overlap"}</h2><div className="signal-list">{data.shared.length?data.shared.map(n=><span key={n}>{n}</span>):<p>Explore a few things to see what connects your worlds.</p>}</div></article><article><small>THEIR WORLD</small><h2>New to you</h2><div className="signal-list">{data.theirs.filter(n=>n.node_type==="concept").slice(0,6).map(n=><span key={n.name}>{n.name}</span>)}</div></article><article><small>YOUR WORLD</small><h2>New to them</h2><div className="signal-list">{data.viewerAvailable?data.yours.filter(n=>n.node_type==="concept").slice(0,6).map(n=><span key={n.name}>{n.name}</span>):<Link href="/login">Sign in to compare both taste maps <ArrowRight size={14}/></Link>}</div></article></div><div className="privacy-note">Taste ID is a public profile label, separate from the private account ID. These signals are aggregates; the owner can revoke this link at any time.</div></>:null}</section><footer className="compare-footer">FIND YOUR NICHE <span>·</span> EXPLORE WHAT CONNECTS</footer></main>;
}
