"use client";
import { useState } from "react";
import { ArrowRight, LoaderCircle, MessageCircle, Send } from "lucide-react";
type Evidence = string | {title:string;url?:string;domain?:string;description?:string};
type Message = { role: "user"|"assistant"; content: string; suggestions?: string[]; evidence?: Evidence[] };
const prompts=["What is my strongest niche?","What have I saved recently?","What is RAG?","Who directed Scarface?"];
export function TasteChat({signals=[],recent=[]}:{signals?:string[];recent?:{title:string;domain?:string}[]}) {
  const [messages,setMessages]=useState<Message[]>([]);const[query,setQuery]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState("");
  async function ask(value=query){const text=value.trim();if(!text||busy)return;setMessages(old=>[...old,{role:"user",content:text}]);setQuery("");setBusy(true);setError("");try{const res=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:text,tasteSignals:signals,localItems:recent})});const data=await res.json();if(!res.ok)throw new Error(data.error??"Your question could not be answered.");setMessages(old=>[...old,{role:"assistant",content:data.answer,evidence:data.evidence,suggestions:data.suggestions}]);}catch(e){setError(e instanceof Error?e.message:"Your question could not be answered.");}finally{setBusy(false);}}
  return <section className="taste-chat" id="chat"><div className="chat-heading"><div><div className="eyebrow"><span className="eyebrow-line"/> A GUIDE TO YOUR NEXT THREAD</div><h2>Ask your <i>taste map.</i></h2><p>Questions about your saved signals stay scoped to your own profile.</p></div><MessageCircle size={23}/></div><div className="chat-window" aria-live="polite">{!messages.length?<div className="chat-prompts"><span>START HERE</span>{prompts.map(p=><button key={p} onClick={()=>ask(p)}>{p}<ArrowRight size={13}/></button>)}</div>:messages.map((m,i)=><article key={`${i}-${m.role}`} className={`chat-message ${m.role}`}><small>{m.role==="user"?"YOU":"FIELD NOTES"}</small><p>{m.content}</p>{m.evidence?.length? <div className="chat-evidence">{m.evidence.slice(0,6).map((x,j)=>typeof x==="string"?<span key={`${x}-${j}`}>{x}</span>:<a key={`${x.title}-${j}`} href={x.url&&/^https:\/\//.test(x.url)?x.url:"#discover"} target={x.url&&/^https:\/\//.test(x.url)?"_blank":undefined} rel="noreferrer"><b>{x.title}</b><small>{x.domain}</small>{x.description&&<span>{x.description}</span>}</a>)}</div>:null}{m.suggestions?.length?<div className="chat-suggestions">{m.suggestions.map(s=><button key={s} onClick={()=>ask(s)}>{s}<ArrowRight size={12}/></button>)}</div>:null}</article>)}{busy&&<div className="chat-thinking"><LoaderCircle className="spin" size={15}/> FINDING THE THREAD…</div>}{error&&<p role="alert" className="chat-error">{error}</p>}</div><form className="chat-form" onSubmit={e=>{e.preventDefault();void ask();}}><input value={query} onChange={e=>setQuery(e.target.value)} aria-label="Ask about your interests" placeholder="Ask what connects your interests…" maxLength={600}/><button disabled={busy||!query.trim()} aria-label="Send question">{busy?<LoaderCircle className="spin" size={16}/>:<Send size={16}/>}</button></form></section>;
}
